# Generated by Django 5.1.7 on 2026-02-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_image_game_rawg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='rawg_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
