# Generated by Django 5.1.7 on 2026-02-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_genre_alter_game_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rawg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
