# Generated by Django 5.x on 2026-02-20 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_game_players"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameRating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField(default=1000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(on_delete=models.CASCADE, to="games.game"),
                ),
            ],
            options={
                "ordering": ["-rating"],
                "unique_together": {("user", "game")},
            },
        ),
    ]
