# Generated by Django 5.1.7 on 2026-02-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
